### ISSUE TITLE
Support for Iris 1.6.11+

### ISSUE THREAD

**Issue by NolanHewitt** [leon-o/iris-flw-compat#96] opened 2024-02-04 05:03 UTC
Will support for the newer versions of iris and flywheel be added?

**Comment by w568w** [comment] 2024-02-05 15:04
I found a version compatible with Iris 1.6.11 in [the comment section of mcmod](https://www.mcmod.cn/class/7283.html) and confirmed that it works.

I assume it should be the result of someone's work on a fork, but the commenter did not cite the source. There are many forks of this repository, and I am not sure which one exactly.

And here is the jar file:

<https://wwmb.lanzouw.com/in0UQ1kg32ve>, code: Fish.

**Comment by BADtochka** [comment] 2024-02-12 01:33
> I found a version compatible with Iris 1.6.11 in [the comment section of mcmod](https://www.mcmod.cn/class/7283.html) and confirmed that it works.
> 
> I assume it should be the result of someone's work on a fork, but the commenter did not cite the source. There are many forks of this repository, and I am not sure which one exactly. The mod file itself has no indication, either.
> 
> Anyway, here is the .jar file:
> 
> https://wwmb.lanzouw.com/in0UQ1kg32ve, code: Fish.

it seems to be working, thanks

**Comment by wsox98** [comment] 2024-02-13 00:12
This is very helpful thank you! Is there a version that works for Minecraft 1.20.1?

**Comment by Mourdraug** [comment] 2024-02-15 20:48
The support for the 1.6.11+ is already merged, instead of downloading binaries from an unknown Chinese source I'd strongly urge to just grab the source from this repo and simply run "gradlew build" to build it yourself

**Comment by w568w** [comment] 2024-02-16 03:06
> The support for the 1.6.11+ is already merged

Thanks for your reminder, I have edited my original comments.

**Comment by w568w** [comment] 2024-02-17 03:27
> is it possible to build one for 1.20.1? or is that not a thing yet :'D

It is much easier to build for 1.20.1 than other versions because master branch ***is*** for 1.20.1 now :) 

Just clone it, run `./gradlew build` and you are all set. If versions are mismatched, change them in [gradle.properties](https://github.com/leon-o/iris-flw-compat/blob/main/gradle.properties).

**Comment by leon-o** [comment] 2024-02-19 10:12
I have uploaded the latest version to CurseForge. Besides, is there anyone interested in co-maintaining this project? I may not be able to dedicate too much time to this mod, so updates might be a bit infrequent.

**Closed by leon-o** 2024-02-19 10:12 UTC
