### ISSUE TITLE
Moving components of Create blocks do not render

### ISSUE THREAD

**Issue by Sneumorin** [leon-o/iris-flw-compat#112] opened 2024-04-05 02:23 UTC
With Complimentary shaders (Reimagined) enabled, moving parts of Create buildings do not render, and occasionally create very large graphical errors. This is only the case with this mod enabled, and with these shaders. Disabling real-time shadows does not resolve the issue:

Iris-Flywheel-Compat disabled
![2024-04-04_22 13 48](https://github.com/leon-o/iris-flw-compat/assets/144089577/0ec971bc-d5e1-4c41-a061-276f3ec3173d)

Iris-Flywheel-Compat enabled
![2024-04-04_22 20 37](https://github.com/leon-o/iris-flw-compat/assets/144089577/5ebbc9fb-46e1-42c9-962f-f19df149774d)
![2024-04-04_22 20 45](https://github.com/leon-o/iris-flw-compat/assets/144089577/4508bea5-6b6d-4ba8-95b4-976ed5b5e50e)

-MC Ver. 1.18.2
-Latest mod ver.

**Comment by Sneumorin** [comment] 2024-04-11 00:10
Update for clarification in my original issue, as well as a few things @SebastianMeinberger reminded me of:

- Machine specs:
Nvidia GTX 1060 - GPU
Intel Core i5 8400 - CPU
Windows 10 64-bit - OS

- Issue still persists over other versions of this mod, as well as with Embeddium installed.
- Issue persists while switched to multiple shader packs listed on the mod's page as "compatible"

**Comment by LikeManTV** [comment] 2024-04-15 10:13
I can confirm as I have similar issues. Moving parts do not render and I see graphical issues all over the screen.
- Shaderpack: Complementary Reimagined
- Specs:
  GPU - Nvidia RTX 3060 Ti
  CPU - AMD Ryzen 5 5600
  OS - Windows 11 64-bit

**Comment by ninjaeon** [comment] 2024-04-19 15:41
> I've got this issue as well. Using latest Iris Flywheel Compat version from CurseForge:
> 
> * Fabric 1.20.1
> * iris-flywheel-compat-1.20.1-0.2.4
> * iris-mc1.20.1-1.6.17
> * create-fabric-0.5.1-f-build.1417+mc1.20.1
> 
> Full Log: https://mclo.gs/pE6f5xs

Disabling EuphoriaPatcher-0.3.0-fabric or switching to a non-EuphoriaPatches enabled Shader solved this issue for me.

**Comment by ChloeDawn** [comment] 2024-05-02 21:29
Setting `Shadow Sample Quality` to `Very Low` fixed this for me.

**Comment by AmazeingGames** [comment] 2024-05-07 01:50
I had this issue while using [Emeddium ](https://www.curseforge.com/minecraft/mc-mods/embeddium) on 1.19.2. However I've since switched to [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) and [Rubidium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras), which fixed most issues I had with create rendering and allowed me to use this mod with a huge performance boost.

**Comment by SevenChords** [comment] 2024-06-22 18:21
Tested on a Mac Studio, same issue, disabling this mod fixes the rendering of contraptions that are invisible with this mod enabled

**Comment by leon-o** [comment] 2024-08-06 14:19
Same issue with #89, which is fixed by commit 3d07f64.

**Closed by leon-o** 2024-08-06 14:19 UTC
