### ISSUE TITLE
Blocks in contraptions don't render when shaderpack real-time shadows are enabled

### ISSUE THREAD

**Issue by adueppen** [leon-o/iris-flw-compat#59] opened 2023-07-14 05:33 UTC
I'm using:
- Forge 47.1.0 on 1.20.1
- Create 0.5.1.d
- Oculus 1.6.4
- Rubidium 0.4.20
- Oculus Flywheel Compat 0.2.0
- Complementary Reimagined shaders

This is running on Linux, with an AMD RX 6800 XT GPU. When the real-time shadows in this or any other shaderpack are enabled, contraptions fail to render any ordinary blocks that are part of them. Disabling this mod fixes the issue, but at the expense of reasonable framerates.

Mod enabled:
![2023-07-14_00 21 55](https://github.com/leon-o/iris-flw-compat/assets/6982070/48d3455d-1956-4edd-97c0-727635b81c46)

Mod disabled:
![2023-07-14_00 21 01](https://github.com/leon-o/iris-flw-compat/assets/6982070/681cec25-82e6-45c1-ab22-0dc832c4e27c)

**Comment by MaximilianHollis** [comment] 2023-08-08 02:16
I can attest to these findings with rendering set to instancing. In addition, there is some serious log spam:
![image](https://github.com/leon-o/iris-flw-compat/assets/50596827/b395a2d5-8858-414b-b76a-f5085efb419a)

![image](https://github.com/leon-o/iris-flw-compat/assets/50596827/3df507c9-f92f-4125-9e42-767f4c8acfbf)
and the Complementary Re-imagined shaderpack.

**Comment by fentriesjava** [comment] 2023-11-04 13:21
this is still an issue with 0.2.1, at least on fabric
- fabric loader 0.14.24
- fabric api 0.90.4
- sodium 0.5.3
- iris 1.6.10
- create 0.5.1d from  https://github.com/Treetrain1/Create
- iris flywheel compat 0.2.1
- complimentary reimagined (but is an issue with any shader)

also running on linux with a 6800 XT. did anyone either of you find a workaround?

**Comment by amyfromearth** [comment] 2023-11-13 21:45
Confirmed this is happening for me as well.

**Comment by Arikelliott** [comment] 2023-11-22 05:10
Happening on my end as well. RX 6800 XT on Linux. Currently playing the Create Astral modpack. Viewing a contraption while shaders are enabled brings my framerate down into single digits, gives me the `GL_INVALID_OPERATION in glDrawElements` error repeatedly in my logs, and most blocks in the contraptions don't render.

Disabling real-time shadows does seem to fix it, at least in the Complimentary-based shaderpacks (I haven't tested any others yet).

Currently using:

- OS: Linux
- GPU: RX 6800 XT
- Minecraft version 1.18.2
- Fabric Loader 0.14.22
- Create 0.5.0.i
- Sodium 0.4.1
- Iris 1.6.10
- Iris Flywheel Compat 0.2.0
- Tested with Complimentary Reimagined, Complimentary Unbound, BSL, AstraLex, and MakeUp UltraFast. All of them have the same issue.

**Comment by branan** [comment] 2023-11-25 20:36
I've been googling around for exactly the same Create Astral issue. I'm away from my home PC for a couple more days for the US holiday, but will test if disabling real-time shadows also fixes the issue for me.

**Comment by branan** [comment] 2023-12-05 03:29
I was able to confirm that turning off real-time shadows fixes the issue for me. I was unfortunately not able to get any debugging done - both RenderDoc and ApiTrace cause java to crash immediately if I try to launch minecraft with them loaded.

**Comment by branan** [comment] 2023-12-15 01:06
I got ApiTrace working, and managed to track this down :sunglasses: 

The issue is that Create's `ContraptionProgram` [hardcodes one of its samplers](https://github.com/Fabricators-of-Create/Create/blob/49cc17e3de33c965b1c409130abe436821f7410c/src/main/java/com/simibubi/create/content/contraptions/render/ContraptionProgram.java#L28), which causes a conflict with Iris.

I've tested rebuilding Create with that sampler set to `31` (just to get it way out of the range that Iris might use), and things seem to work now?

I _think_ the correct fix for this is probably to try to use a Mixin to override the [Iris list of reserved samplers](https://github.com/IrisShaders/Iris/blob/8bc3a7ef7da23d082592f2c356a5ae313d4f4ccd/src/main/java/net/coderbot/iris/samplers/IrisSamplers.java#L33), but that is far beyond my java skills to implement as a quick PR to this repo without doing a lot more learning about how Mixins work.

**Comment by branan** [comment] 2023-12-15 02:54
Sorry for the issue update spam, but I dug through the Mixin docs and got this fixed!

The PR is in #86, but for anyone who feels like trusting a jar from a stranger on the internet, you can replace `iris-flywheel-compat-1.18.2-0.2.0.jar` in your `mods` folder with [my version](https://drive.proton.me/urls/N7QWXZ8638#kjKRByQ2FlKx)

**Comment by Arikelliott** [comment] 2023-12-15 03:45
My good friend, you're amazing.

I can confirm the fix is working on my end. I tested with the same set of shaders as last time, all are working fine even with realtime shadows re-enabled.

**Comment by Etroll780** [comment] 2024-01-04 01:11
> Sorry for the issue update spam, but I dug through the Mixin docs and got this fixed!
> 
> The PR is in #86, but for anyone who feels like trusting a jar from a stranger on the internet, you can replace `iris-flywheel-compat-1.18.2-0.2.0.jar` in your `mods` folder with [my version](https://drive.proton.me/urls/N7QWXZ8638#kjKRByQ2FlKx)

WIll this work as a replacement for the Oculus equivalent compatibility mod?

**Closed** 2024-01-09 14:25 UTC
