### ISSUE TITLE
Add Support for Oculus 1.6.13 & Embeddium 0.2.14

### ISSUE THREAD

**Issue by KelvinZhang512** [leon-o/iris-flw-compat#91] opened 2023-12-25 04:38 UTC
Game failed to launch while the latest version of embeddium and oculus is installed.
[crash-2023-12-25_12.35.00-client.txt](https://github.com/leon-o/iris-flw-compat/files/13763926/crash-2023-12-25_12.35.00-client.txt)

**Comment by SentinelX101** [comment] 2023-12-28 13:23
I can also confirm this issue due to the latest update of Oculus 1.6.13. A fix for it would be great if possible

**Comment by nirp-s** [comment] 2024-01-15 06:21
Yes, a fix for this would be amazing. Oculus 1.6.13 is the first time I've ever seen shaders work with Distant Horizons, but now the problem is Flywheel Compat, so I have to choose between Distant Horizons with Oculus 1.6.13 or Flywheel Compat with Oculus 1.6.9.

**Comment by jam-jar-binks** [comment] 2024-01-19 06:39
error occured here as well, interestingly enough its the same error that occours with oculus 1.6.9 1.19.2 patched for Distant Horizons

**Closed** 2024-02-15 14:04 UTC
